---
name: Deploy API
on:
  push:
    branches: [main, flow]
  workflow_dispatch:  # So it's possible to manually retrigger the action
jobs:
  deploy-api:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Compose production .env file
        run: make compose-dotenv
      - name: Restart PM2 instance
        run: pm2 restart library-api
